# Fonts (Matches your Polybar JetBrains Nerd Font)
#font_family      Monospace Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        9.0

# Window layout and transparency
window_padding_width 4
background_opacity 0.85
dynamic_background_opacity yes

# Colors (Classic Dark Theme)
foreground #FF0000
background #000000

# Use 'none' to enable reverse-video selection (preserves syntax colors)
selection_foreground none
selection_background none


# Terminal bell (Disable the annoying beep)
enable_audio_bell no

# Cursor shape and blinking
cursor #FF0000
cursor_shape block
cursor_blink_interval 0.5
cursor_stop_blinking_after 0

# Stop Zsh from forcing the cursor into a line
shell_integration no-cursor

# Stop Kitty from checking for Wayland to make it launch instantly
linux_display_server x11
